import Footer from '@/components/footer/Footer';
import Navbar from '@/components/navbar/Navbar';
import Sidebar from '@/components/sidebar/Sidebar';
import { Inter } from "next/font/google";
import ReduxProvider from './Provider';
import "./globals.css";

const inter = Inter( { subsets: ["latin"] } );

export const metadata = {
  title: "ShopEase",
  description: "Generated by create next app",
};

export default function RootLayout( { children } ) {
  return (
    <html lang="en">
      <body className={ `${inter.className} overflow-hidden` }>
        <ReduxProvider>
          <Navbar />
          <div className='md:hidden'>
            <Sidebar />
          </div>
          { children }
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
