import Footer from '@/components/footer/Footer';
import Navbar from '@/components/navbar/Navbar';
import Sidebar from '@/components/sidebar/Sidebar';
import { Roboto } from 'next/font/google';
import ReduxProvider from './Provider';
import "./globals.css";

const roboto = Roboto( {
  weight: ["100", '300', '400', '500', '700', '900'],
  subsets: ['latin'],
  display: 'swap',
} );

export const metadata = {
  title: "ShopEase",
  description: "Generated by create next app",
};

export default function RootLayout( { children } ) {
  return (
    <html lang="en">
      <body className={ `${roboto.className}` }>
        <ReduxProvider>
          <Navbar />
          <div className='md:hidden'>
            <Sidebar />
          </div>
          { children }
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
